### ISSUE TITLE
alter .gitignore generated by setup

### ISSUE THREAD

**Issue by jduss4** [CDRH/datura#134]
Had to alter the gitignore file for cather-complete-letters in this way in order to see NEW production files (not just modified existing files)

```
 /output/*
 # increase specificity of this path if you wish to only track generated html
+!/output/production
 !/output/production/html
```

**Comment by techgique** [comment]
```
/output/*
!/output/production
# Remove line above and increase specificity of the path to only track specific changes
# For example, only track generated html
#!/output/production/html
```

I think we'd want the final output to look like this to be extra clear?

**Comment by jduss4** [comment]
We need that last line to be uncommented for sure, since in general we always want to track the production html, but I'm fine with changing the word choice, sure

**Comment by techgique** [comment]
Ah okay. If we want to keep it for insurance so HTML is always tracked, I think that should probably be spelled out in a comment and moved above the comments describing possible changes. And we should use another example for tracking other production files more specifically. You might have a better idea for said example though.

```
/output/*
# Always track production HTML output
!/output/production/html

!/output/production
# Modify line above, increasing specificity of the path
# to only track specific production changes (in addition to HTML)
# For example, only track Elasticsearch files:
#!/output/production/es
```

**Comment by jduss4** [comment]
Just FYI, I guess I'm not entirely sure how the gitignore files are ultimately added up, but I think order matters?  We'd have to test it out a bit.  I think that the `!/output/production` line needs to be above `!/output/production/html` or else it won't negate the `/output/*` part.  I had fussed with it a little the other day and that was at least my preliminary finding, although I also wasn't specifically looking into the line order.

**Comment by jduss4** [comment]
Ah, perhaps the order doesn't matter?  From the gitignore docs:

```
When deciding whether to ignore a path, Git normally checks gitignore patterns from multiple sources, with the following order of precedence, from highest to lowest (within one level of precedence, the last matching pattern decides the outcome):
```

**Comment by techgique** [comment]
Ah, I forgot about the order. I think you're right and the more specific part should be moved to the end.

That part you copied from the docs is about which source the list of files to ignore is coming from, not the order they're listed within said files.

**Comment by jduss4** [comment]
Ah yup, you're right

**Comment by jduss4** [comment]
Although instead of modifying the line, we should say "add" because the `!/output/production` should not be altered

**Comment by techgique** [comment]
:thinking:  People will either need to modify that line, or comment it out and add another more specific path below. How about something like this:

```
/output/*

# Comment this line if you don't want to track all production changes
!/output/production

# If above commented, add a line with a more specific path
# to track selective production changes (in addition to HTML)
# For example, selectively track Elasticsearch files:
# !/output/production/es

# Always track production HTML changes
!/output/production/html
```

**Comment by jduss4** [comment]
Maybe we should talk about this out loud, I think I'm not explaining myself very clearly.  You need both the `!/output/production` AND the `!/output/production/html` lines in that order in order to "un-ignore" the `/output/*` line.

```
/output/*


# Always track production HTML changes
!/output/production
!/output/production/html

# Track production changes for output formats
# Add the full path to the directory after !/output/production
# To track other environment output changes, you will need
# both to unignore the environment and the output format directories
```

Sorry, I hadn't really intended this issue to become a large discussion, it was more of a reminder for me to fix the current gitignore "setup" step missing one of those lines of the gitignore file.

**Comment by techgique** [comment]
Confirmed this behavior by testing. Looking at docs (https://git-scm.com/docs/gitignore) I think this is the relevant line:
>  It is not possible to re-include a file if a parent directory of that file is excluded.

I think to enable selectively backing up inside `/output/production` we'd need to add that directory's contents back to the ignore list after un-ignoring the directory itself:

```
/output/*   # /output/production is ignored

!/output/production  # /output/production AND all its contents are un-ignored

/output/production/*  # /output/production itself is un-ignored, but contents are all ignored

/output/production/es  # Selective directory un-ignored
```

So updated suggested layout would be like
```
/output/*

# Always track changes within production
!/output/production

# Un-comment this to selectively track production changes
#/output/production/*
# Add path to track selective production changes (in addition to HTML)
# For example, selectively track Elasticsearch files:
# !/output/production/es

# Always track production HTML changes
!/output/production/html
```

**Comment by jduss4** [comment]
Thanks for confirming that's the behavior you're seeing too.  I'm a little confused by some of your lines, like
`/output/production/es  # Selective directory un-ignored`
but I'm assuming that's just a typo?
I also just tested on the cather-complete-letters repo and if you don't include the `/output/production/*` line then ES changes ARE being tracked, so I think that we probably want that line always uncommented.

I'd like to keep this fairly simple because for the most part, as far as I am aware, the only thing we want to track is production html and tracking other output types will be rare (unless if our current workflow changes, or if we're "archiving" sites or something).

I hope you don't feel like I'm ignoring your suggestions, but I'm worried it might be a little overkill for the setup script.  Perhaps we could document the gitignore steps in datura's docs directory?

Here's my counter-proposal for the `bin/setup` script:

```
# ignore all output types except for production html
/output/*
!/output/production
/output/production/*
!/output/production/html

# add more production subpaths if you wish to track more production output types
# example: !/output/production/es
# if you would like to track other environment output types,
# imitate the pattern above:
# !/output/environment
# !/output/environment/*
# !/output/environment/type
```

??

**Comment by jduss4** [comment]
I realize I "oh no yours is overkill" and then made mine several lines longer.....lol.  I think mine just has more demo and less explanation, but also I could cut the last four or so lines with the demo-ey part since they aren't needed really

**Comment by jduss4** [comment]
The good news is that I didn't realize that I had to also have `/output/production/*` to make sure that ES and Solr were being ignored, so this process has paid off :)

**Comment by techgique** [comment]
You're right, it was a typo in the first snippet in my last message. The last line should have been
```
!/output/production/es  # Selective directory un-ignored
```

And the pendulum swings back... typo on the second to last line in your counter-proposal with an unwanted leading `!` :upside_down_face:

I'm cool with the pared down version for us:
```
# ignore all output types except for production html
/output/*
!/output/production
/output/production/*
!/output/production/html
```

My explanation was assuming that non-dev team members might be tweaking the file, so I wanted it to be clear what each line was doing. If it's just us, we can figure it out from this short version :+1:

**Comment by jduss4** [comment]
Haha!
Sounds good, I'll push it this morning
