### ISSUE TITLE
bump to v0.1.1 cannot run binaries without bundle exec

### ISSUE THREAD

**Issue by jduss4** [CDRH/datura#138]
when the 0.1.1 release came out, I noticed that when installing it into a ruby 2.6.0 brand new gemset, running an executable gives you the following error:

```
$ about
Traceback (most recent call last):
	2: from /usr/local/rvm/gems/ruby-2.6.0@datura_whitman-0.1.1/bin/about:23:in `<main>'
	1: from /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem datura (>= 0.a) with executable about (Gem::GemNotFoundException)
```

Workaround is to use `bundle exec [command]` instead, which, though probably the officially recommended way to call the binaries, is not as friendly for staff / students.

Updating the version in an existing 2.5.3 gemset seems fine, binaries are still discoverable from there

**Comment by jduss4** [comment]
Tried fresh 2.5.3 directory with new gemset and version 0.1.1 and it works fine, so I'm guessing this is related to ruby 2.6.0 in some way...?

**Comment by jduss4** [comment]
In some cases this is still bombing out on 2.5.3
```
Traceback (most recent call last):
	2: from /usr/local/rvm/gems/ruby-2.5.3@datura_whitman-0.1.1/bin/about:23:in `<main>'
	1: from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem datura (>= 0.a) with executable about (Gem::GemNotFoundException)

```

**Comment by jduss4** [comment]
Suspecting this is not related to a version of datura, but rather to something about rvm or bundler.

If I take a 2.5.3 ruby repository locked to datura 0.1.0 which currently works by typing `about`, then run `bundle install`, despite the fact that Gemfile.lock is not updated, now you have to use `bundle exec about` instead.

This was tested with rvm 1.29.1 and bundler 1.17.1

**Comment by techgique** [comment]
Apologies if you've already read all this before, but I don't recall having heard you mention this `rubygems-bundler` gem or the command `gem regenerate_binstubs`: https://rvm.io/integration/bundler

Appears that's how RVM documents getting around the need for `bundle exec`

**Comment by jduss4** [comment]
Oooh awesome, that definitely looks like it's in the right direction!  Sadly, a quick 5 minute pass before a meeting was unsuccessful....datura isn't being included for some reason (possibly due to its gemspec or configuration or something?)

```
whitman-leavesofgrass $ gem regenerate_binstubs
try also: gem pristine --binstubs
bundler 2.0.1
bundler 1.17.3
irb 1.0.0
nokogiri 1.8.5
rake 12.3.2
rdoc 6.1.0
rest-client 2.0.2
rubygems-update 3.0.2
```

I'll revisit this when I'm back!

**Comment by jduss4** [comment]
I think that the RVM hook solution worked!!!  I'm going to try it a few more places, whoo hoo!  Thanks!

**Comment by jduss4** [comment]
For reference, with rvm 1.29.4 I have the following hooks available :

```
after_cd_bundler
after_cd_install_vendored_gems
after_install_auto_gem
after_install_codesign
after_use_current
after_use_home_bin
after_use_jruby
after_use_jruby_opts
after_use_maglev
after_use_rbx_opts
after_use_textmate
```

I did the following:

```
chmod +x $rvm_path/hooks/after_cd_bundler
cd /path/to/project
bundle install --binstubs=./bundler_stubs
```

It detected datura right away!  Not sure why the `gem regenerate_binstubs` did not, but might be worth looking into separately, since I have to use an extra step to get datura installed locally than gem documentation makes it look like I should have to do

**Comment by jduss4** [comment]
....what the heck?  This worked for one repository but not for another.  I will keep investigating.  :(

**Comment by jduss4** [comment]
Here's the warning you get when moving into a directory which has had the rvm hook treatment (first time, only):

```
The bundler binstubs directory is in the current directory, which may be unsafe.
Consider using rubygems-bundler instead => https://github.com/rvm/rubygems-bundler
Remove the BUNDLE_BIN line from .bundle/config to disable this prompt.
Are you sure you want to add the bundler binstubs directory to the path?
(anything other than 'Yes' will cancel) > 
```

**Comment by techgique** [comment]
So am I correct in my understanding, that it generates a directory of binaries that wrap the Ruby code?

:thinking: Is the warning showing because you didn't install the `rubygems-bundler` gem before running `gem regenerate_binstubs`? Is that optional, or does it affect where it saves the binstubs?

I'm guessing the `rubygems-bundler` is probably a gem we'd want to install globally for each version of Ruby in RVM to avoid having to add it to `Gemfile`s?

**Comment by techgique** [comment]
But this is an exciting development in maintaining the easier commands for posting etc! :smile:

**Comment by jduss4** [comment]
This issue appears to be resolved in later versions by redoing the the ruby wrapper!
