### ISSUE TITLE
Fix --update

### ISSUE THREAD

**Issue by jduss4** [CDRH/datura#143]
When things were moved to Datura::Parser this got broken:

https://github.com/CDRH/datura/blob/57e26f834a222860fcfa0071635d770ba6f7f529/lib/datura/parser_options/post.rb#L62

```
gems/datura/lib/datura/parser_options/post.rb:62:in `block (2 levels) in post_params': uninitialized constant Datura::Parser::Parser (NameError)
Did you mean?  Datura::Parser
```

**Comment by techgique** [comment]
`s/Parser/this/`? :thinking:

**Comment by jduss4** [comment]
Should be an easy fix, but my brain needs me to finish the api_bridge / orchid stuff before I open up this can of worms!  :X
