### ISSUE TITLE
Ideas for multiple projects

### ISSUE THREAD

**Issue by karindalziel** [CDRH/datura#63]
This applies specifically to Whitman right now, but I could see using it for others. 
- Make the ability to have sub folders within projects, wo instead of whitman-correspondence you could have a whitman folder with correspondence
- since it's assumed those within a "project" will be writing to the same index, let the user set the index(es) for an entire project. 
- change clear script to refer to only the sub project - the best way to do this would probably be by using the slug property, but perhaps not. Maybe we need to add another field for subprojects.

**Comment by karindalziel** [comment]
I think the last point will be handled by the new api, not sure about the first two

**Comment by jduss4** [comment]
Check out the data_cather repository for an example of this
Probably not a great idea for whitman because of the sheer amount of files? but maybe we should consider putting together multiple sections that are similar?
