### ISSUE TITLE
Add back in "shortname" or some other variable

### ISSUE THREAD

**Issue by karindalziel** [CDRH/datura#89]
Here's the problem I am running into: 

I need to change the XSL to build the media server URL's. Right now the media_base looks like this: 

`media_base: https://cdrhmedia.unl.edu`

So in order to build the complete URL, I need to add

`images/cather-complete-letters`

but I don't know that I want to pull cather-complete-letters fromt he folder name because the actual repo name is "complete letters" and the folder name could be different on different servers. 

As Jess and I talked about it, I realized that since the folder name will never be committed to the repo it's probably not the best basis for building path URL's. Jess proposed we add a new variable, "folder_name" which will be passed through for things that require the folder path, and then add "shortname" back in. (ugh, sorry)

I'm open to other names besides "shortname" though - namespace? something else?

**Comment by techgique** [comment]
Something like "namespace", "context", or "scope" sounds nicer :)

**Comment by karindalziel** [comment]
yeah, I'm leaning towards namespace. I'm trying to think of different contexts we might use this - building media URL's what else?

**Comment by techgique** [comment]
"abbreviation"?
"abbreviname" 👍  hehe

**Comment by jduss4** [comment]
I'm closing this because I hate it but also now you can add anything you want
