### ISSUE TITLE
Version data with collections

### ISSUE THREAD

**Issue by jduss4** [CDRH/datura#95]
Come up with a workflow / system to make sure that big changes to the data repo don't require changing ALL the collections immediately.

Brainstorming:
- alter data repo to be an includable gem or similar per collection
- use multiple data directory locations (this is complicated because of html / xml file locations)
- hook to verify pulls to data repo on different servers (for example, whitman server whose data repo may not be updated as frequently)

**Comment by jduss4** [comment]
The data repository as a gem sounds very attractive to me, and would solve some problems like about how an update to the data repo might require a change to multiple collections.....I'm going to think about this a little.

**Comment by techgique** [comment]
Logging both the version of the data repo and the collection repo alongside generated HTML may help. Files that have been modified but not committed could still leave room for confusion there though. :grimacing:

**Comment by jduss4** [comment]
Yahoo we made a gem!
